/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miscelania2;

import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author tadeo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cont = new javax.swing.JPanel();
        Empleado = new javax.swing.JButton();
        Cliente = new javax.swing.JButton();
        Orden = new javax.swing.JButton();
        DetalleO = new javax.swing.JButton();
        producto = new javax.swing.JButton();
        pedido = new javax.swing.JButton();
        detallep = new javax.swing.JButton();
        proveedor = new javax.swing.JButton();
        telefonopro = new javax.swing.JButton();
        telefonoemp = new javax.swing.JButton();
        bitacora = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        Fondo.setBackground(new java.awt.Color(255, 51, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Menu");

        cont.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contLayout = new javax.swing.GroupLayout(cont);
        cont.setLayout(contLayout);
        contLayout.setHorizontalGroup(
            contLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        contLayout.setVerticalGroup(
            contLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 691, Short.MAX_VALUE)
        );

        Empleado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Empleado.setForeground(new java.awt.Color(255, 255, 255));
        Empleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miscelania2/clientem.png"))); // NOI18N
        Empleado.setText("  Empleado");
        Empleado.setBorderPainted(false);
        Empleado.setContentAreaFilled(false);
        Empleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpleadoActionPerformed(evt);
            }
        });

        Cliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Cliente.setForeground(new java.awt.Color(255, 255, 255));
        Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miscelania2/clienteem.png"))); // NOI18N
        Cliente.setText(" Cliente");
        Cliente.setBorderPainted(false);
        Cliente.setContentAreaFilled(false);
        Cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteActionPerformed(evt);
            }
        });

        Orden.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Orden.setForeground(new java.awt.Color(255, 255, 255));
        Orden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miscelania2/ordennm.png"))); // NOI18N
        Orden.setText(" Orden");
        Orden.setBorderPainted(false);
        Orden.setContentAreaFilled(false);
        Orden.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Orden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdenActionPerformed(evt);
            }
        });

        DetalleO.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DetalleO.setForeground(new java.awt.Color(255, 255, 255));
        DetalleO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miscelania2/ordenm.png"))); // NOI18N
        DetalleO.setText(" Detalle de Orden");
        DetalleO.setBorderPainted(false);
        DetalleO.setContentAreaFilled(false);
        DetalleO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DetalleO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetalleOActionPerformed(evt);
            }
        });

        producto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        producto.setForeground(new java.awt.Color(255, 255, 255));
        producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miscelania2/productom.png"))); // NOI18N
        producto.setText("  Producto");
        producto.setBorderPainted(false);
        producto.setContentAreaFilled(false);
        producto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productoActionPerformed(evt);
            }
        });

        pedido.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pedido.setForeground(new java.awt.Color(255, 255, 255));
        pedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miscelania2/pedidom.png"))); // NOI18N
        pedido.setText(" Pedido");
        pedido.setBorderPainted(false);
        pedido.setContentAreaFilled(false);
        pedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidoActionPerformed(evt);
            }
        });

        detallep.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        detallep.setForeground(new java.awt.Color(255, 255, 255));
        detallep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miscelania2/detallepm.png"))); // NOI18N
        detallep.setText(" Detalle Pedido");
        detallep.setBorderPainted(false);
        detallep.setContentAreaFilled(false);
        detallep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        detallep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detallepActionPerformed(evt);
            }
        });

        proveedor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        proveedor.setForeground(new java.awt.Color(255, 255, 255));
        proveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miscelania2/proveedorm.png"))); // NOI18N
        proveedor.setText("  Proveedor");
        proveedor.setBorderPainted(false);
        proveedor.setContentAreaFilled(false);
        proveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedorActionPerformed(evt);
            }
        });

        telefonopro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        telefonopro.setForeground(new java.awt.Color(255, 255, 255));
        telefonopro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miscelania2/TELPRO.png"))); // NOI18N
        telefonopro.setText("Telefono Proveedor");
        telefonopro.setBorderPainted(false);
        telefonopro.setContentAreaFilled(false);
        telefonopro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        telefonopro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoproActionPerformed(evt);
            }
        });

        telefonoemp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        telefonoemp.setForeground(new java.awt.Color(255, 255, 255));
        telefonoemp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miscelania2/telemp.png"))); // NOI18N
        telefonoemp.setText("Telefono Empleado");
        telefonoemp.setBorderPainted(false);
        telefonoemp.setContentAreaFilled(false);
        telefonoemp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        telefonoemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoempActionPerformed(evt);
            }
        });

        bitacora.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bitacora.setForeground(new java.awt.Color(255, 255, 255));
        bitacora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miscelania2/bitm.png"))); // NOI18N
        bitacora.setText(" Bitacora");
        bitacora.setBorderPainted(false);
        bitacora.setContentAreaFilled(false);
        bitacora.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bitacora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bitacoraActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miscelania2/554.png"))); // NOI18N

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Orden, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DetalleO)
                    .addComponent(producto)
                    .addComponent(jLabel2)
                    .addComponent(pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonopro)
                    .addComponent(Empleado)
                    .addComponent(telefonoemp, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detallep)
                    .addComponent(bitacora, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1))
                    .addComponent(Cliente))
                .addGap(18, 18, 18)
                .addComponent(cont, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Orden, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DetalleO, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(producto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(detallep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefonopro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefonoemp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bitacora))
                    .addComponent(cont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpleadoActionPerformed
        // TODO add your handling code here:
        try {
        Empleado p2 = new Empleado();
            p2.setSize(1000,1000);
        p2.setLocation(0,0);
        cont.removeAll();
        cont.add(p2,BorderLayout.CENTER);
        cont.revalidate();
        cont.repaint();
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EmpleadoActionPerformed

    private void ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteActionPerformed
        try {
            // TODO add your handling code here:
            Cliente p1=new Cliente();
            p1.setSize(986,900);
            p1.setLocation(0,0);
            cont.removeAll();
            cont.add(p1,BorderLayout.CENTER);
            cont.revalidate();
            cont.repaint();
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_ClienteActionPerformed

    private void OrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdenActionPerformed
        try {
            // TODO add your handling code here:
            Orden p3=new Orden();
            p3.setSize(986,900);
            p3.setLocation(0,0);
            cont.removeAll();
            cont.add(p3,BorderLayout.CENTER);
            cont.revalidate();
            cont.repaint();
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
             
    }//GEN-LAST:event_OrdenActionPerformed

    private void DetalleOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetalleOActionPerformed
        try {
            // TODO add your handling code here:
            DetalleOrden p4=new DetalleOrden();
            p4.setSize(986,900);
            p4.setLocation(0,0);
            cont.removeAll();
            cont.add(p4,BorderLayout.CENTER);
            cont.revalidate();
            cont.repaint();
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DetalleOActionPerformed

    private void productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productoActionPerformed
        try {
            // TODO add your handling code here:
            Producto p6=new Producto();
            p6.setSize(986,900);
            p6.setLocation(0,0);
            cont.removeAll();
            cont.add(p6,BorderLayout.CENTER);
            cont.revalidate();
            cont.repaint();
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_productoActionPerformed

    private void pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidoActionPerformed
        try {
            // TODO add your handling code here:
            Pedido p7=new Pedido();
            p7.setSize(986,900);
            p7.setLocation(0,0);
            cont.removeAll();
            cont.add(p7,BorderLayout.CENTER);
            cont.revalidate();
            cont.repaint();
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pedidoActionPerformed

    private void proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedorActionPerformed
        try {
            // TODO add your handling code here:
            Proveedor p9=new Proveedor();
            p9.setSize(986,900);
            p9.setLocation(0,0);
            cont.removeAll();
            cont.add(p9,BorderLayout.CENTER);
            cont.revalidate();
            cont.repaint();
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_proveedorActionPerformed

    private void detallepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detallepActionPerformed
        try {
            // TODO add your handling code here:
            DetallePedido p8=new DetallePedido();
            p8.setSize(986,900);
            p8.setLocation(0,0);
            cont.removeAll();
            cont.add(p8,BorderLayout.CENTER);
            cont.revalidate();
            cont.repaint();
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_detallepActionPerformed

    private void telefonoempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoempActionPerformed
        try {
            // TODO add your handling code here:
            TelefonoE p5=new TelefonoE();
            p5.setSize(986,848);
            p5.setLocation(0,0);
            cont.removeAll();
            cont.add(p5,BorderLayout.CENTER);
            cont.revalidate();
            cont.repaint();
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_telefonoempActionPerformed

    private void bitacoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bitacoraActionPerformed
        // TODO add your handling code here:
        Bitacora p15 = new Bitacora();
        p15.setSize(986,848);
        p15.setLocation(0,0);
        cont.removeAll();
        cont.add(p15,BorderLayout.CENTER);
        cont.revalidate();
        cont.repaint();
    }//GEN-LAST:event_bitacoraActionPerformed

    private void telefonoproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoproActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            TelefonoP p10 = new TelefonoP();
            p10.setSize(986,900);
            p10.setLocation(0,0);
            cont.removeAll();
            cont.add(p10,BorderLayout.CENTER);
            cont.revalidate();
            cont.repaint();
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_telefonoproActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cliente;
    private javax.swing.JButton DetalleO;
    private javax.swing.JButton Empleado;
    private javax.swing.JPanel Fondo;
    private javax.swing.JButton Orden;
    private javax.swing.JButton bitacora;
    private javax.swing.JPanel cont;
    private javax.swing.JButton detallep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton pedido;
    private javax.swing.JButton producto;
    private javax.swing.JButton proveedor;
    private javax.swing.JButton telefonoemp;
    private javax.swing.JButton telefonopro;
    // End of variables declaration//GEN-END:variables
}
